main:thesis.tex \
	preface/cover.tex \
	body/gaishu.tex body/huanjing.tex body/jielun.tex body/kaifa.tex \
	body/sheji.tex body/xuqiu.tex body/yunxing.tex body/zhixie.tex \
	reference/reference.tex \
	setup/format.tex setup/package.tex
	pdflatex thesis.tex
.PHONY:clean
clean:
	-rm *.aux *.out *.thm *.log 
	-rm */*.aux
